### ISSUE TITLE
There is no version 2.0.4 on CRAN

### ISSUE THREAD

**Issue by jdistlr** [TommyJones/textmineR#26]
At the moment textmineR fails while installing text2vec (0.4.0) and textmineR (2.0.3) via CRAN. With this configuration textmineR's tokenizing behavior is struggeling. For example GetTopTerms delivers chunks of sentences instead of single terms.

Thanks for your great work!

**Comment by TommyJones** [comment]
Thanks for using textmineR and for opening the issue! Because of CRAN
policies, I can only update monthly. So, I will be pushing 2.0.4 to CRAN at
the end  of the week. Unfortunately, I rushed the last patch because
text2vec 0.4 hit CRAN a couple days before I was to present on textmineR.
In my rush to get a working version before the presentation, I made a patch
that was not effective. I  am sorry.

If you want to wait a week or so, 2.04. will be on CRAN. In the meantime,
if you have devtools installed, you can get the working version of
textmineR with `devtools::install_github("TommyJones/textmineR")`

**Comment by jdistlr** [comment]
Hi Tommy and thanks for your fast reply. Unfortunately i can't wait for a week and the clients working with textmineR are behind a http_proxy ... so it's quite complicated to get devtools to work. Is there another possibility (on windows) getting textmineR to work?

Maybe by loading .Rproj and compiling locally? I tried that way ... then I get a textmineR_2.0.4.zip file in my local drive (D:\). How to load that into R space? RStudio still shows the textmineR 2.0.2 package.

**Comment by TommyJones** [comment]
Is the issue that you can't install a C++ compiler, can't install devtools,
or can install devtools, but can't make it access github from the client
site?

If you can't install a C++ compiler (like that which comes with Rtools),
there's no way to build from source; I'm sorry.

If you have a compiler, but can't install devtools, just unzip the 2.0.4
zipfile you have into some directory, "mydirectory" and type
`install.packages("mydirectory", repos = NULL, type = "source")`

If you have a compiler, can install devtools, but can't point it to github
from the client end, unzip the file as above and type
`devtools::install("mydirectory")

The big difference between the second and third option is that the third
option install dependencies as if you were installing from CRAN. The second
option installs textmineR only and no dependencies. You'd have to get those
yourself.

The final option: if you can build binaries on your local machine but can't
do it from the client site, you can build the 2.0.4 binaries using one of
the above methods. Then go into wherever you have R install libraries, find
the textmineR folder and copy its contents to the client site wherever
their R installation looks for libraries.


On Wed, Nov 2, 2016 at 2:34 PM jdistlr <notifications@github.com> wrote:

Hi Tommy and thanks for your fast reply. Unfortunately i can't wait for a
week and the clients working with textmineR are behind a http_proxy ... so
it's quite complicated to get devtools to work. Is there another
possibility (on windows) getting textmineR to work?

Maybe by loading .Rproj and compiling locally? I tried that way ... then I
get a textmineR_2.0.4.zip file in my local drive (D:). How to load that
into R space? RStudio still shows the textmineR 2.0.2 package.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/TommyJones/textmineR/issues/26#issuecomment-257958575>,
or mute the thread

**Comment by WilDoane** [comment]
@jdistlr To build textmineR from source, you would first have to install RTools, the build tool kit for R. I used the 3.3 version today to build textmineR successfully: https://cran.r-project.org

Once that's installed, unzip the textmineR-master.zip file you downloaded from https://github.com/TommyJones/textmineR/archive/master.zip

in R/RStudio, 

    install.packages("c:/Users/yourusername/Downloads/textmineR-master/", type = "source", repos = NULL)

changing the path to wherever you unzipped the textmineR source code.

**Comment by jdistlr** [comment]
Wonderful. Thanks for all your guidance.
Now I'm on version 2.0.4.
