### ISSUE TITLE
Thinning/Lag of the sampler

### ISSUE THREAD

**Issue by love-borjeson** [TommyJones/textmineR#73]
textmineR is awesome! I'm in the process of migrating from topicmodels package. The only thing I miss is a tool for calculating perplexity for a series of k.

anyhow, to my question:

What are the 'thinning-practices' (if any) used by 'FitLdaModel'? I noticed that the package topicmodels uses iterations=thinning which is alien to me mainly because of [this ](http://www.cs.colorado.edu/~jbg/docs/2014_emnlp_howto_gibbs.pdf). But what is default in textmineR?

Closely related: what are the averaging strategies: are all samples after burnin saved or just a few, or just the best (with respect to maximum likelihood)?

best regards,
Love (a name, not a greeting :-) Börjeson

**Comment by TommyJones** [comment]
Hi! Thanks for using textmineR! I'd be happy to look into adding a perplexity function at some point in the future. In the short run, I tend to use the mean of `CalcProbCoherence` as a guide to picking the number of topics. I'll be the first to admit it doesn't have the same theoretical justification though.

The short answer is that I don't use really thinning at all in textmineR. Though there is a more complicated explanation to be had. 

All samples after burnin are averaged to make the final `phi` and `theta` matrices. However this happens by just adding the matrices of counts (`theta_counts` for example) at the current iteration to a running total and then I divide by the number of post-burn in iterations. In other words, the samples themselves are not saved or discarded, but they're all used. Traditionally with Bayesian stats, you'd save all the samples and then figure out if you need thinning and then discard based on your analysis. However in this case, we'd run the risk of a memory blow up, so that's not an option.

Also, if you use the option `calc_likelihood = TRUE`, the likelihood is only computed every 10 iterations. So, to be candid, you're not getting the purest form of convergence analysis, and it looks like the samples themselves may be thinned when they're actually not.

In a future version, I could imagine letting the user pre-determine a thinning strategy which would dictate both how frequently to calculate the log likelihood and how many samples to discard.

Does that help?

**Comment by love-borjeson** [comment]
Tommy, that's a great answer, and very helpful. Thank you!

**Comment by TommyJones** [comment]
Awesome. Closing the issue now.
