### ISSUE TITLE
Prior information on topics  (e.g. Seeded LDA/Guided LDA)

### ISSUE THREAD

**Issue by dominiqueemmanuel** [TommyJones/textmineR#77]
Hi,

Thank you for this great package. From my experience `textmineR::FitLdaModel` produces some of the best quality topics in R (for medium-sized corpus).

This is an enhancement issue: do you think it would be possible to allow a “seeded LDA” or “guided LDA” in the next versions (i.e. introduce prior information corresponding to known topics with known words)?
A simple way would be to introduce a parameter that represents initial assignments of words to topics in each document (as the parameter `initial` in the `lda::lda.collapsed.gibbs.sample` function).

Best regards,
Dominique

**Comment by TommyJones** [comment]
Hi Dominique,

I have some good news. That functionality is *technically* available in textmineR already. That said, I'll keep the issue open for two reasons: I haven't added a vignette on the topic and I could probably make it easier to do. (I implemented this feature about a year ago, but didn't get it to 100% of what I wanted. I've been slowly working on it since. Hence the lack of publication/fanfare.)

(Slightly long post follows.)

## Hacking `update` to set prior topics

There is an `update` method for topic model objects spit out by `FitLdaModel`. This `update` method takes `phi` from a previous model as a prior for words over topics. It also allows you to add new topics.  So, if one wanted to seed some topics you could essentially create a list with elements `phi`, `alpha`, and `beta`. Then re-assign its class to "`lda_topic_model`".

``` 
my_phi <- "some matrix"
my_alpha <- 0.1

my_prior <- list(phi = my_phi, alpha = my_alpha)

class(my_prior) <- "lda_topic_model"
```

Make sure that you ensure the rows of your `phi` sum to 1. 

Then you should be able to call `update` with your new DTM etc. (Basically, at this point follow the examples from `help("fit.lda_topic_model")`. 

## Next steps (and why I stopped short of publicizing the update method)

Another way to update a topic model is to keep the old prior, but continue updating counts from a previous model. I've been working on that (and I think I have a good way to do it). But it requires a major refactor of the C++ code. I've been working on that for the last month or so. Maybe it'll be done by new year?

## Adding a function or arguments to make initializing a model 

I'll do some thinking about a more intuitive way to seed topics rather than hacking the `update` method. I'm open to suggestions. My gut says that arguments + vignette is probably the way to go here.

**Comment by dominiqueemmanuel** [comment]
Thanks for your detailled answer!

I'm going to experiment with your suggestion (using `update` function).

Best regards!
Dominique

**Comment by dominiqueemmanuel** [comment]
Hi Tommy,


I have experimented with `update` function and I don't know if/where I made a mistake but it seems to me that the prior information introduced with `phi` is vanishing after just a few iterations.

Let me explain.

First I build a fictive corpus with a fictive topic.
```
library(text2vec)
library(textmineR)
library(magrittr)

# (1/3) build fictive corpus -----------------------
vocab <- c("word1 word2", "word1 word3", paste0("word", 4:1000))
set.seed(123)
p0 <- runif(length(vocab) - 2)
p0 <- p0 / sum(p0)
txt <- sapply(1:500, function(t) {
  p1 <- sample(c(1e-6, 0.2), 1)
  # p is prob the probability of "word1 word2" or "word1 word3"
  # p is either almost 0 either 0.2

  p2 <- (1 - p1) * p0
  n <- sample(500:1000, 1)
  p <- c(p1 / 2, p1 / 2, p2)
  paste0(sample(vocab, n, replace = TRUE), collapse = " ")
})
# (2/3) dtm and let's see the fictive topic  -----------------------
it <- itoken(txt)
v <- create_vocabulary(it)
dtm <- create_dtm(it, vocab_vectorizer(v))

# there is a fictive topic with words "word1","word2"and ""word3"
x1 <- 1 * (dtm[, "word1"])
x2 <- 1 * (dtm[, "word2"])
x3 <- 1 * (dtm[, "word3"])
cor(cbind(x1, x2, x3))
#              x1          x2          x3
# x1 1.0000000 0.740780646 0.675938630
# x2 0.7407806 1.000000000 0.005672986
# x3 0.6759386 0.005672986 1.000000000
# "word2" is correlated to "word1"
# "word1" is correlated to "word2" and "word3"

w <- setdiff(v$term, c("word1", "word2", "word3"))
max(cor(dtm[, c("word1", "word2", "word3")] %>% as.matrix(), dtm[, w] %>% as.matrix()))
# 0.2046946
# "word1","word2" and "word3" are not correlated to others words
```
Then let me show what surprises me
```
# (3/3) LDA with high priors on first topic and word "word2" (so that a word of the fictive topic has a high prior)
# Parameters
NC <- 10 # number of topics
NV <- ncol(dtm) # size of vocabulary
phi <- matrix(1 / NV, nrow = NC, ncol = NV)
phi[1, ] <- 0.001 / NV
alpha <- rep(0.1, NC)
m <- c("word2")
im <- which(colnames(dtm) %in% "word2") # high prior for "word2" on first topic
phi[1, im] <- 0.999 / length(im)
phi <- phi / (phi %>% rowSums())
colnames(phi) <- colnames(dtm)
priors <- list(phi = (phi), alpha = alpha, beta = 1e-2)
class(priors) <- "lda_topic_model"

# lda
set.seed(123)
model <- textmineR:::update.lda_topic_model(priors, dtm, iterations = 1, optimize_alpha = FALSE)
```
There is a high prior on "word2"
```
priors$phi[1, ] %>%
  sort(decreasing = TRUE) %>%
  head()
# word2      word496      word373       word76      word107      word794
# 9.990010e-01 1.000001e-06 1.000001e-06 1.000001e-06 1.000001e-06 1.000001e-06
```
However the posterior of phi after just 1 iteration erase (almost completely) the prior information on "word2"
```
model$phi[1, ] %>%
  sort(decreasing = TRUE) %>%
  head()
# word748     word918     word459     word467       word2     word659
# 0.002917927 0.002122129 0.002122129 0.002095602 0.002095337 0.002016022
```

and after two iterations:
```
set.seed(123)
model <- textmineR:::update.lda_topic_model(model, dtm, iterations = 1, optimize_alpha = FALSE)
# 
model$phi[1, ] %>%
  sort(decreasing = TRUE) %>%
  head()
# word748     word876     word376     word918     word297      word29
# 0.002937979 0.002249430 0.002090662 0.002064545 0.001985084 0.001958531
```

And don’t know if I am wrong, but this result surprises me. I would expect that the first topic should be “composed” of `"word2"` (and then by `"word1"` and `"word3"` too) but this is not the case (after 2 iteration `"word2"` has not a high `phi` value, and after 100 iterations it is of course also the case).
Do you have any idea on what it is happening?

Best regards,
Dominique

**Comment by TommyJones** [comment]
I'll take a deeper look at this over the weekend and see if I can parse what's happening.

**Comment by TommyJones** [comment]
I suspect that what's happening is that the data is overriding the prior. The posterior for a given $\phi_{k,v}$ is $\frac{c_{k,v} + \beta_{k,v}}{\sum_k c_{k,v} + \beta_{k,v}}$. Here, $c_{k,v}$ is the number of times token $v$ was sampled for topic $k$. Also, I'm indexing $\beta$ as a matrix, since we're using a matrix prior (the old $\Phi$) here.

It's likely that the count (i.e. the pattern in the data) is dominating the prior. One thing that might help would be to set the magnitude of $\beta$ to a large number to make the prior stronger.  That can have funky effects itself when training a regular LDA model, but here it might help.

**Comment by dominiqueemmanuel** [comment]
Thank you!

Indeed playing with the norm of $beta$ (increasing it) allows to get more intuitive results with this example (i.e. it allows `word2` to have high $phi$ value, and it even allows a high value for `word1` too).

Maybe a real guided LDA (wih pre-affected words to topics) may be a finer approach, but setting a prior to $phi$ (or $beta$) is already a good thing!

Best regards,
Dominique

**Comment by TommyJones** [comment]
Closing out this issue. I'm working on a new LDA package, [tidylda](https://github.com/TommyJones/tidylda). Eventually, textmineR will wrap tidylda for its LDA functionality. (The logic is that textmineR is going to grow into a topic modeling work bench where you can swap out different models with the same syntax/naming conventions. But the computational engines for the models themselves will be in other packages.)

Anyway, I've [migrated the issue](https://github.com/TommyJones/tidylda/issues/8) over to tidylda which allows you to set matrix priors at the time of fitting rather than having to hack it as suggested on this thread.
