### ISSUE TITLE
test

### ISSUE THREAD

**Issue by prstern01** [TommyJones/textmineR#89]

**Comment by TommyJones** [comment]
Hi, I think this is an issue with rsparse and better opened on its issue
page <https://github.com/rexyai/rsparse/issues>. But I'll share a couple
thoughts if they are helpful.

You might want to consider upgrading your R installation. Recently rsparse
went through a big refactoring because it was having compilation issues on
several systems. I don't know if yours was affected. But a newer version of
R and its corresponding version of rsparse could help. Second, the output
should show exactly what the C++ compilation error was. That'll be more
helpful to diagnose why rsparse isn't compiling for you than the final R
error.
