### ISSUE TITLE
How to use the Mallet in textmineR?

### ISSUE THREAD

**Issue by moomoofarm1** [TommyJones/textmineR#94]
Hi,

It is said in your topic modeling vignette [article](https://www.rtextminer.com/articles/c_topic_modeling.html), the package supports topic models from mallet.

> Fit a topic model using your desired package (for example, [mallet](https://cran.r-project.org/package=mallet))

But I cannot find any example code showing this feature.

Could you please add the code or relevant links to the vignette article?

Regards,
Alex

**Comment by TommyJones** [comment]
Hi apologies for the long delayed response. 

I haven't explicitly implemented this feature; you'd have to do the formatting yourself. But to expand on the workflow at the bottom of the article.

1. Load your documents into R.
2. Use `CreateDtm` or `CreateTcm` to create a DTM or TCM.
3. Do any vocabulary editing you want to do, so that your matrix has the right tokens etc for your analysis. 
4. If, for example, your DTM is named `dfm`, call `Dtm2Docs(dtm)` to create a character vector of tokens in the frequencies in `dtm`. This is necessary for MALLET because it expects documents as input, not a matrix. 
5. Load the resulting "documents" into MALLET. This may involve writing the result in (4) out to text files. The MALLET extension in R may allow you to pass a character vector. I don't remember.
6. Run your topic model in MALLET.
7. Extract the results of the MALLET topic model and reconstruct a `theta` matrix and `phi` matrix. `theta` has one row per document and one column for topic. Each row should sum to 1, with the entries representing P(topic|document). `phi` has one row per topic and one column per token. Each row should sum to 1, with the entries representing P(token|topic). I am not familiar enough with MALLET's outputs to tell you exactly how to do this. The `tidytext` package has "tidiers" for MALLET output that might be helpful.
8. Store the results of 7 in a named list to make your life easier, or don't. :)
9. Call whichever analysis functions you want from `textmineR` and pass your `phi` and `theta` and `dtm` as arguments.

By the way, textmineR is not being actively developed anymore. You might wish to consider moving to [`tidylda`](https://cran.r-project.org/package=tidylda).
